<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="chrome=1">

    

    <title>
      JS-错误处理 | SPACE-19 
    </title>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    
    

    <meta name="description" content="一、在执行JavaScript代码的时候，有些情况下会发生错误。二、错误分两种： 1. 一种是程序写的逻辑不对，导致代码执行异常。对于这种错误，要修复程序。 例如： 12var s = null;var len = s.length; // TypeError：null变量没有length属性  2. 一种是执行过程中，程序可能遇到无法预测的异常情况而报错。 例如，网络连接中断，读取不存在的文件，">
<meta name="keywords" content="JS">
<meta property="og:type" content="article">
<meta property="og:title" content="JS-错误处理 | SPACE-19">
<meta property="og:url" content="http://yoursite.com/2017/06/05/JS-错误处理/index.html">
<meta property="og:site_name" content="SPACE-19">
<meta property="og:description" content="一、在执行JavaScript代码的时候，有些情况下会发生错误。二、错误分两种： 1. 一种是程序写的逻辑不对，导致代码执行异常。对于这种错误，要修复程序。 例如： 12var s = null;var len = s.length; // TypeError：null变量没有length属性  2. 一种是执行过程中，程序可能遇到无法预测的异常情况而报错。 例如，网络连接中断，读取不存在的文件，">
<meta property="og:updated_time" content="2017-06-05T01:32:05.940Z">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="JS-错误处理 | SPACE-19">
<meta name="twitter:description" content="一、在执行JavaScript代码的时候，有些情况下会发生错误。二、错误分两种： 1. 一种是程序写的逻辑不对，导致代码执行异常。对于这种错误，要修复程序。 例如： 12var s = null;var len = s.length; // TypeError：null变量没有length属性  2. 一种是执行过程中，程序可能遇到无法预测的异常情况而报错。 例如，网络连接中断，读取不存在的文件，">
    
    
    
      <link rel="icon" type="image/x-icon" href="favicon.png">
    
    <link rel="stylesheet" href="/css/uno.css">
    <link rel="stylesheet" href="/css/highlight.css">
    <link rel="stylesheet" href="/css/archive.css">
    <link rel="stylesheet" href="/css/china-social-icon.css">

</head>
<body>

    <span class="mobile btn-mobile-menu">
        <i class="icon icon-list btn-mobile-menu__icon"></i>
        <i class="icon icon-x-circle btn-mobile-close__icon hidden"></i>
    </span>

    

<header class="panel-cover panel-cover--collapsed">


  <div class="panel-main">

  
    <div class="panel-main__inner panel-inverted">
    <div class="panel-main__content">

        

        <h1 class="panel-cover__title panel-title"><a href="/" title="link to homepage">SPACE-19</a></h1>
        <hr class="panel-cover__divider" />

        
        <p class="panel-cover__description">
          XD
        </p>
        <hr class="panel-cover__divider panel-cover__divider--secondary" />
        

        <div class="navigation-wrapper">

          <nav class="cover-navigation cover-navigation--primary">
            <ul class="navigation">

              
                
                <li class="navigation__item"><a href="/archive" title="" class="">归档</a></li>
              
                
                <li class="navigation__item"><a href="/#blog" title="" class="blog-button">首页</a></li>
              
                
                <li class="navigation__item"><a href="/about" title="" class="">关于</a></li>
              

            </ul>
          </nav>

          <!-- ----------------------------
To add a new social icon simply duplicate one of the list items from below
and change the class in the <i> tag to match the desired social network
and then add your link to the <a>. Here is a full list of social network
classes that you can use:

    icon-social-500px
    icon-social-behance
    icon-social-delicious
    icon-social-designer-news
    icon-social-deviant-art
    icon-social-digg
    icon-social-dribbble
    icon-social-facebook
    icon-social-flickr
    icon-social-forrst
    icon-social-foursquare
    icon-social-github
    icon-social-google-plus
    icon-social-hi5
    icon-social-instagram
    icon-social-lastfm
    icon-social-linkedin
    icon-social-medium
    icon-social-myspace
    icon-social-path
    icon-social-pinterest
    icon-social-rdio
    icon-social-reddit
    icon-social-skype
    icon-social-spotify
    icon-social-stack-overflow
    icon-social-steam
    icon-social-stumbleupon
    icon-social-treehouse
    icon-social-tumblr
    icon-social-twitter
    icon-social-vimeo
    icon-social-xbox
    icon-social-yelp
    icon-social-youtube
    icon-social-zerply
    icon-mail

-------------------------------->

<!-- add social info here -->



        </div>

      </div>

    </div>

    <div class="panel-cover--overlay"></div>
  </div>
</header>

    <div class="content-wrapper">
        <div class="content-wrapper__inner entry">
            

<article class="post-container post-container--single">

  <header class="post-header">
    
    <h1 class="post-title">JS-错误处理</h1>

    

    <div class="post-meta">
      <time datetime="2017-06-05" class="post-meta__date date">2017-06-05</time> 

      <span class="post-meta__tags tags">

          

          
             &#8226; 标签:
            <font class="tags">
              <a class="tags-link" href="/tags/JS/">JS</a>
            </font>
          

      </span>
    </div>
    
    

  </header>

  <section id="post-content" class="article-content post">
    <p>一、在执行JavaScript代码的时候，有些情况下会发生错误。<br>二、错误分两种：</p>
<pre><code>1. 一种是程序写的逻辑不对，导致代码执行异常。对于这种错误，要修复程序。
例如：
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div></pre></td><td class="code"><pre><div class="line">var s = null;</div><div class="line">var len = s.length; // TypeError：null变量没有length属性</div></pre></td></tr></table></figure>

2. 一种是执行过程中，程序可能遇到无法预测的异常情况而报错。
例如，网络连接中断，读取不存在的文件，没有操作权限等。
对于这种错误，就需要处理它，并可能需要给用户反馈。
</code></pre><p>三、错误处理是程序设计时必须要考虑的问题。有些贴近系统底层的语言(如C)，错误是通过错误码返回的，不过这种方式表示错误在编写程序时十分不便。因此，高级语言通常都提供了更抽象的错误处理逻辑：<code>try ... catch ... finally</code>，JavaScript也不例外。</p>
<ul>
<li><p>使用<code>try ... catch ... finally</code>处理错误时，上例代码编写如下：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div><div class="line">14</div><div class="line">15</div><div class="line">16</div></pre></td><td class="code"><pre><div class="line">var r1, r2, s = null;</div><div class="line">try</div><div class="line">&#123;</div><div class="line">  r1 = s.length; // 此处应产生错误</div><div class="line">  r2 = 100; // 该语句不会执行</div><div class="line">&#125; </div><div class="line">catch (e)</div><div class="line">&#123;</div><div class="line">  alert(&apos;出错了：&apos; + e);</div><div class="line">&#125;</div><div class="line">finally </div><div class="line">&#123;</div><div class="line">  console.log(&apos;finally&apos;);</div><div class="line">&#125;</div><div class="line">console.log(&apos;r1 = &apos; + r1); // r1应为undefined</div><div class="line">console.log(&apos;r2 = &apos; + r2); // r2应为undefined</div></pre></td></tr></table></figure>
<p>运行后可发现，弹出的Alert提示类似“出错了：TypeError: Cannot read property ‘length’ of null”。</p>
</li>
<li><p>try … catch … finally的执行流程</p>
<ul>
<li><code>try { ... }</code>包裹的那部分代码表示在执行过程中可能会发生错误，一旦发生错误就不再继续执行后续代码，转而跳到catch块。</li>
<li><code>catch (e) { ... }</code>包裹的代码就是错误处理代码，变量<code>e</code>表示捕获到的错误。</li>
<li>最后，无论有没有错误，finally一定会被执行。</li>
<li>总结执行流程：<ol>
<li>先执行<code>try { ... }</code>的代码；</li>
<li>有错误发生时，执行到出错的语句，后续语句不再继续执行，转而执行<code>catch (e) { ... }</code>代码；没有错误发生时，<code>catch (e) { ... }</code>代码不会被执行；</li>
<li>最后执行`finally { … }代码。</li>
</ol>
</li>
</ul>
</li>
<li><p><code>catch</code>和<code>finally</code>可以不必都出现。即try语句一共有三种形式：</p>
<ol>
<li>完整的<code>try ... catch ... finally</code></li>
<li>只有<code>try ... catch，没有finally</code></li>
<li>只有<code>try ... finally，没有catch</code></li>
</ol>
</li>
</ul>
<p>四、错误类型<br>JavaScript有一个标准的<code>Error对象</code>表示错误，还有从<code>Error</code>派生的<code>TypeError、ReferenceError</code>等错误对象。在处理错误时，可以通过<code>catch(e)</code>捕获的<code>变量e</code>（也可以用其他变量名命名）来访问错误对象。<br>    <figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div><div class="line">14</div><div class="line">15</div><div class="line">16</div><div class="line">17</div></pre></td><td class="code"><pre><div class="line">try &#123;</div><div class="line">   ...</div><div class="line">&#125; </div><div class="line">catch (e)&#123;</div><div class="line">   if (e instanceof TypeError) </div><div class="line">   &#123;</div><div class="line">      alert(&apos;Type error!&apos;);</div><div class="line">   &#125;</div><div class="line">   else if (e instanceof Error) </div><div class="line">   &#123;</div><div class="line">      alert(e.message);</div><div class="line">   &#125;</div><div class="line">   else </div><div class="line">   &#123;</div><div class="line">      alert(&apos;Error: &apos; + e);</div><div class="line">   &#125;</div><div class="line">&#125;</div></pre></td></tr></table></figure></p>
<p>五、抛出错误</p>
<ul>
<li>程序也可以主动抛出一个错误，让执行流程直接跳转到<code>catch</code>块。</li>
<li>抛出错误使用<code>throw</code>语句。</li>
<li>JavaScript允许抛出任意对象，包括数字、字符串。但最好还是抛出一个<code>Error</code>对象。</li>
<li><p>例如下面的代码让用户输入一个数字，程序接收到的实际上是一个字符串，然后用parseInt()转换为整数。当用户输入不合法的时，就抛出错误：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div><div class="line">14</div><div class="line">15</div><div class="line">16</div></pre></td><td class="code"><pre><div class="line">var r, n, s;</div><div class="line">try </div><div class="line">&#123;</div><div class="line">    s = prompt(&apos;请输入一个数字&apos;);</div><div class="line">    n = parseInt(s);</div><div class="line">    if (isNaN(n)) </div><div class="line">    &#123;</div><div class="line">        throw new Error(&apos;输入错误&apos;);// 主动抛出错误</div><div class="line">    &#125;</div><div class="line">    // 计算平方:</div><div class="line">    r = n * n;</div><div class="line">    alert(n + &apos; * &apos; + n + &apos; = &apos; + r);</div><div class="line">&#125; </div><div class="line">catch (e) &#123;</div><div class="line">    alert(&apos;出错了：&apos; + e);</div><div class="line">&#125;</div></pre></td></tr></table></figure>
</li>
<li><p>实际上JavaScript允许抛出任意对象，包括数字、字符串。但最好还是抛出一个<code>Error</code>对象。</p>
</li>
<li>当用<code>catch</code>捕获错误时，一定要编写错误处理语句。哪怕仅仅把错误打印出来（<code>console.log(e);</code>），也不要什么也不干。</li>
</ul>
<p>六、错误传播</p>
<ul>
<li>如果在一个函数内部发生了错误，它自身没有捕获，错误就会被抛到外层调用函数；如果外层函数也没有捕获，该错误会一直沿着函数调用链向上抛出，直到被JavaScript引擎捕获，代码终止执行。</li>
<li>所以不必在每一个函数内部捕获错误，只需要在合适的地方来个统一捕获，一网打尽。至于在哪些地方捕获错误比较合适，需要视情况而定。</li>
<li>实例：<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div><div class="line">14</div><div class="line">15</div><div class="line">16</div><div class="line">17</div><div class="line">18</div><div class="line">19</div><div class="line">20</div><div class="line">21</div><div class="line">22</div><div class="line">23</div><div class="line">24</div><div class="line">25</div><div class="line">26</div><div class="line">27</div><div class="line">28</div><div class="line">29</div><div class="line">30</div></pre></td><td class="code"><pre><div class="line">//3.main()函数有try ... catch语句，所以错误最终在main()函数被处理了</div><div class="line">function main(s)</div><div class="line">&#123;</div><div class="line">    console.log(&apos;BEGIN main()&apos;);</div><div class="line">    try &#123;</div><div class="line">        foo(s);</div><div class="line">    &#125; </div><div class="line">    catch (e) &#123;</div><div class="line">      alert(&apos;出错了：&apos; + e);</div><div class="line">    &#125;</div><div class="line">    console.log(&apos;END main()&apos;);</div><div class="line">&#125;</div><div class="line"></div><div class="line">//2. foo()函数没有try ... catch语句，所以错误继续向上抛给调用方main()函数</div><div class="line">function foo(s)  </div><div class="line">&#123;</div><div class="line">  console.log(&apos;BEGIN foo()&apos;);</div><div class="line">  bar(s); </div><div class="line">  console.log(&apos;END foo()&apos;);</div><div class="line">&#125;</div><div class="line"></div><div class="line">//1.当bar()函数传入参数null时代码会报错，错误会向上抛给调用方foo()函数</div><div class="line">function bar(s)</div><div class="line">&#123;</div><div class="line">  console.log(&apos;BEGIN bar()&apos;);</div><div class="line">  console.log(&apos;length = &apos; + s.length); </div><div class="line">  console.log(&apos;END bar()&apos;);</div><div class="line">&#125;</div><div class="line"></div><div class="line">main(null);</div></pre></td></tr></table></figure>
</li>
</ul>
<p>七、异步错误处理</p>
<ul>
<li>JavaScript引擎是一个事件驱动的执行引擎，代码总是以单线程执行，而回调函数的执行需要等到下一个满足条件的事件出现后，才会被执行。</li>
<li><p>例如：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div></pre></td><td class="code"><pre><div class="line">//先执行打印done操作，1秒后才会执行回调函数printTime()</div><div class="line">function printTime() &#123;</div><div class="line">  console.log(&apos;It is time!&apos;);</div><div class="line">&#125;</div><div class="line">setTimeout(printTime, 1000);</div><div class="line">console.log(&apos;done&apos;);</div></pre></td></tr></table></figure>
</li>
<li><p>如上面<code>printTime()函数</code>内部发生了错误，用<code>try</code>包裹<code>setTimeout()</code>是无效的。原因就在于调用<code>setTimeout()函数</code>时，传入的<code>printTime函数</code>并未立刻执行！紧接着，JavaScript引擎会继续执行<code>console.log(&#39;done&#39;);</code>语句，而此时并没有错误发生。直到1秒钟后，执行<code>printTime函数</code>时才发生错误，但此时除了在<code>printTime函数</code>内部捕获错误外，外层代码并无法捕获。</p>
</li>
<li>所以，涉及到异步代码，无法在调用时捕获的原因就是<code>捕获时回调函数并未执行</code>。因此异步代码要在<code>函数内部</code>捕获错误!</li>
<li>类似地当处理一个事件时，在绑定事件的代码处(外面)无法捕获事件处理函数的错误。所以要在事件处理函数<code>内部</code>对相应语句进行捕获。</li>
</ul>

  </section>

  
  
</article>


            <footer class="footer">

    <span class="footer__copyright">&copy; 2014-2015. | 由<a href="https://hexo.io/">Hexo</a>强力驱动 | 主题<a href="https://github.com/someus/huno">Huno</a></span>
    
</footer>
        </div>
    </div>

    <!-- js files -->
    <script src="/js/jquery.min.js"></script>
    <script src="/js/main.js"></script>
    <script src="/js/scale.fix.js"></script>
    

    

    <script type="text/javascript" src="//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
    <script type="text/javascript"> 
        $(document).ready(function(){
            MathJax.Hub.Config({ 
                tex2jax: {inlineMath: [['[latex]','[/latex]'], ['\\(','\\)']]} 
            });
        });
    </script>


    

    <script src="/js/awesome-toc.min.js"></script>
    <script>
        $(document).ready(function(){
            $.awesome_toc({
                overlay: true,
                contentId: "post-content",
            });
        });
    </script>


    
    
    <!--kill ie6 -->
<!--[if IE 6]>
  <script src="//letskillie6.googlecode.com/svn/trunk/2/zh_CN.js"></script>
<![endif]-->

</body>
</html>
